sim: Fix csr.json not found error
When running the simulator in the project directory, as instructed by
README.md:

    $ ./sim.py
    ...
    Traceback (most recent call last):
      File "./sim.py", line 242, in <module>
	main()
      File "./sim.py", line 236, in main
	soc.generate_dts(board_name)
      File "./sim.py", line 176, in generate_dts
	with open(json_src) as json_file, open(dts, "w") as dts_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'build/sim/csr.json'

Due to the os.chdir(), the current directory is changed to the parent
directory of the project, and the csr.json file cannot be found.

Fix this dropping the os.chdir() call.

Fixes: acffa47e621e11f8 ("add dts auto-generation with litex json export and initial json2dts.py script")
Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>